# Generated by Django 4.2.5 on 2024-07-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_siteconfig_cookie_preference_siteconfig_copyright_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="cite_score_link",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="journal",
            name="impact_factor_link",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
