# Generated by Django 4.2.5 on 2024-07-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_journal_cite_score_link_journal_impact_factor_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleauthor",
            name="prefix",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=10,
                null=True,
                verbose_name="Prefix",
            ),
        ),
        migrations.AddField(
            model_name="manuscriptsubmission",
            name="invoice",
            field=models.FileField(
                blank=True, null=True, upload_to="invoices", verbose_name="Invoice"
            ),
        ),
        migrations.AddField(
            model_name="manuscriptsubmission",
            name="published_link",
            field=models.TextField(
                blank=True, null=True, verbose_name="Published Link"
            ),
        ),
        migrations.AddField(
            model_name="manuscriptsubmission",
            name="send_acceptance_letter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manuscriptsubmission",
            name="send_reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manuscriptsubmission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated On"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="footer_copyright",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscriptsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACKNOWLEDGED", "ACKNOWLEDGED"),
                    ("IN_REVIEW", "IN_REVIEW"),
                    ("REVISION", "REVISION"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                    ("PUBLISHED", "PUBLISHED"),
                ],
                default="ACKNOWLEDGED",
                max_length=64,
                verbose_name="Status",
            ),
        ),
    ]
