# Generated by Django 4.2.5 on 2024-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_manuscriptsubmission_additional_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalRanking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="journal_rankings")),
                ("link", models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="submission_email",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="support_email",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="whatsapp",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
